import random

movie = [];
movie.append("Big Miracle | Netflix")
movie.append("Big Fat Liar | Netflix")
movie.append("Big Time Movie | Netflix")
movie.append("Bruno and Boots: Go Jump in the Pool | Netflix")
movie.append("Christopher Robin | Netflix")
movie.append("Earth to Echo | Netflix")
movie.append("From Japan to Egypt | Netflix")
movie.append("Harriet the Spy: Blog Wars | Netflix")
movie.append("Hey Arnold! The Jungle Movie | Netflix")
movie.append("Jinxed | Netflix")
movie.append("Kids on the Block | Netflix")
movie.append("Looney Tunes: Back in Action | Netflix")
movie.append("Mary and The Witch's Flower | Netflix")
movie.append("Miracle | Netflix")
movie.append("Motu Patlu: King of Kings | Netflix")
movie.append("New York Minute | Netflix")
movie.append("Pup Star: Better 2Gether | Netflix")
movie.append("Puppy Star Christmas | Netflix")
movie.append("Radio Rebel | Netflix")
movie.append("Rock My Heart | Netflix Official Site")
movie.append("Rugrats Go Wild | Netflix")
movie.append("Rugrats in Paris: The Movie | Netflix")
movie.append("Shorts | Netflix")
movie.append("Tarzan 2 | Netflix")
movie.append("The Adventure Club | Netflix")
movie.append("The Adventures of Tintin | Netflix")
movie.append("The Guardian Brothers | Netflix")
movie.append("The Princess Switch | Netflix Official Site")
movie.append("The Rugrats Movie | Netflix")
movie.append("The Short Game | Netflix Official Site")
movie.append("Tom and Jerry: The Magic Ring | Netflix")
movie.append("Walk. Ride. Rodeo. | Netflix Official Site")
movie.append("White Fang | Netflix Official Site")
movie.append("Zokkomon | Netflix")
movie.append("Charlotte's Web (1973)| Amazon Prime Free")
movie.append("The Tractor Mac Show| Amazon Prime Free")
movie.append("Legend Of Sarila| Amazon Prime Free")
movie.append("The Boxcar Children: Surprise Island| Amazon Prime Free")
movie.append("Amanda and the Fox| Amazon Prime Free")
movie.append("My Dad's A Soccer Mom| Amazon Prime Free")
movie.append("Golden Winter| Amazon Prime Free")
movie.append("A Turtle's Tale: Sammy's Adventures| Amazon Prime Free")
movie.append("Ready, Jet, Go!: Back to Bortron 7| Amazon Prime Free")
movie.append("The Lost Medallion| Amazon Prime Free")
movie.append("Ice Princess Lily| Amazon Prime Free")
movie.append("Bernie the Dolphin| Amazon Prime Free")
movie.append("Star Trek: The Motion Picture| Amazon Prime Free")
movie.append("All Creatures Big & Small| Amazon Prime Free")
movie.append("Asterix and the Vikings| Amazon Prime Free")
movie.append("The Stolen Princess| Amazon Prime Free")
movie.append("Imagine That| Amazon Prime Free")
movie.append("Borrowers| Amazon Prime Free")
movie.append("All I Want Is Christmas| Amazon Prime Free")
movie.append("Sox: A Family's Best Friend| Amazon Prime Free")
movie.append("Belle and Sebastian| Amazon Prime Free")
movie.append("Heidi| Amazon Prime Free")
movie.append("Minuscule: Valley Of The Lost Ants| Amazon Prime Free")
movie.append("Alpha and Omega 3: The Great Wolf Games| Amazon Prime Free")
movie.append("Spark: A Space Tail| Amazon Prime Free")
movie.append("Jr. Detective Agency| Amazon Prime Free")
movie.append("Adventures in Odyssey: Escape From the Forbidden Matrix| Amazon Prime Free")
movie.append("Adventures in Odyssey: Go West, Young Man!| Amazon Prime Free")
movie.append("Chitty Chitty Bang Bang| Amazon Prime Free")
movie.append("The Best of Laurel and Hardy (In Color)| Amazon Prime Free")
movie.append("Iron Man 2| Amazon Prime Free")
movie.append("Alone For Christmas| Amazon Prime Free")
movie.append("Fireman Sam: Ultimate Heroes - The Movie| Amazon Prime Free")
movie.append("Ace Of Hearts| Amazon Prime Free")
movie.append("Maya The Bee| Amazon Prime Free")
movie.append("Agent Fox| Amazon Prime Free")
movie.append("Bold Eagles| Amazon Prime Free")
movie.append("The Adventures of Mickey Matson and the Copperhead Treasure| Amazon Prime Free")
movie.append("Top Cat Begins| Amazon Prime Free")
movie.append("Oddball| Amazon Prime Free")
movie.append("The Cat in the Hat Knows a Lot About Camping!| Amazon Prime Free")
movie.append("The Cat in the Hat Knows a Lot About Space!| Amazon Prime Free")
movie.append("Sing and Rhyme with Mother Goose Club| Amazon Prime Free")
movie.append("Odd Squad: The Movie| Amazon Prime Free")
movie.append("Tad: The Lost Explorer| Amazon Prime Free")
movie.append("Wild Kratts: Alaska- Hero's Journey| Amazon Prime Free")
movie.append("A Christmas Tree Miracle| Amazon Prime Free")
movie.append("Gone in 60 Seconds| Amazon Prime Free")
movie.append("Apollo 13| Amazon Prime Free")
movie.append("Azorian: The Raising of the K-129| Amazon Prime Free")
movie.append("The Spy Next Door | Amazon Prime Free")
print( movie[random.randrange(2, 84, 1)] )

